### ISSUE TITLE
H2 used in test profile

### ISSUE THREAD

**Issue by appiepollo14** [appiepollo14/quarkus-realworld-api#76]
H2 is still used as a database kind for the test-profile. This is hardcoded in the `DatabaseIntegrationTest.java`. We should refactor this test, if even needed, to get rid of the H2 database and use PostgreSQL for all profiles.

**Comment by codespearhead** [comment]
Can the tests rely on Quarkus-specific annotations, or should they continue using manual Hibernate configuration?

**Comment by appiepollo14** [comment]
@codespearhead See linked PR. Please provide your feedback. 

I don't see the need for any specific Quarkus annotations in this case. This project aims to showcase Quarkus so if there are any Quarkus specific improvements to be made, please describe so we can discuss.
