### ISSUE TITLE
JWT Quarkus extension

### ISSUE THREAD

**Issue by appiepollo14** [appiepollo14/quarkus-realworld-api#77]
There is a lot of custom JWT code in the project. Quarkus offers out-of-the-box functionality for this through extensions. We should rely on that instead of custom code.

**Comment by codespearhead** [comment]
Indeed!

| Current Library         | Suggested Quarkus Alternative   |
|-------------------------|---------------------------------|
| `org.mindrot.jbcrypt`    | `quarkus-elytron-security`      |
| `com.auth0.java-jwt`     | `quarkus-smallrye-jwt`          |

**Comment by appiepollo14** [comment]
@codespearhead I believe the security-jpa is more suitable than elytron for replacing the bcrypt library. See: https://quarkus.io/guides/security-jpa

**Comment by appiepollo14** [comment]
@codespearhead do you have the cycles to give this one a try? If so I assign it to you. Or should I assign it to myself?

**Comment by codespearhead** [comment]
I'll give it a try right now.

**Comment by codespearhead** [comment]
I'm not familiar enough with the codebase to remove the custom code entirely. However, the first step is replacing the third-party JWT extensions with Quarkus-supported ones, which is what I'm doing in [1] and [2].

[1] https://github.com/appiepollo14/quarkus-realworld-api/pull/82
[2] https://github.com/appiepollo14/quarkus-realworld-api/pull/83
